[project]
name = "rasedi_payment_sdk"
version = "0.0.1"
description = "Python SDK for Rasedi"
requires-python = ">=3.0"
dependencies=[
    "httpx",
    "typing",
    "cryptography",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"